### ISSUE TITLE
更新至Swift 2.0说明及任务领取

### ISSUE THREAD

**Issue by dabing1022** [CocoaChina-editors/Welcome-to-Swift#123]
官方更新历史：[https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/RevisionHistory.html#//apple_ref/doc/uid/TP40014216-CH14-ID142](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/RevisionHistory.html#//apple_ref/doc/uid/TP40014216-CH14-ID142)

## 目标
-  润色修改之前的版本
-  更新至最新的2.0版本，参照着苹果官方最新的文档对照现在的翻译版本，注意增加的内容、修改的内容、删除的内容（可能存在），做到不遗漏。

## 更新章节
-  Basic Setup
-  Interacting with Objective-C APIs
-  Writing Swift Classes with Objective-C Behavior
-  Working with Cocoa Data Types
-  Adopting Cocoa Design Patterns
-  Interacting with C APIs
-  Swift and Objective-C in the Same Project
-  Migrating Your Objective-C Code to Swift
-  Document Revision History（需要添加）

## 如何领取 
[https://github.com/CocoaChina-editors/Welcome-to-Swift/issues](https://github.com/CocoaChina-editors/Welcome-to-Swift/issues) 中留言领取，为保证速度，保证2天内完成。

**Comment by xhr4469** [comment]
nice
