### ISSUE TITLE
02 SwiftTour中的循环控制的小问题

### ISSUE THREAD

**Issue by javenisme** [CocoaChina-editors/Welcome-to-Swift#130]
var firstForLoop = 0
for i in 0..3 {
    firstForLoop += i
}
firstForLoop

此处 '..'操作符被提示，“Use of unresolved identifier '..'”

**Comment by CocoaChina-editors** [comment]
此仓库中的《The Swift Programming Language》一书不建议朋友再参考，建议到 [https://github.com/numbbbbb/the-swift-programming-language-in-chinese](https://github.com/numbbbbb/the-swift-programming-language-in-chinese)来学习。
