### ISSUE TITLE
Welcome-to-Swift/The Swift Programming Language/02Language Guide/06Functions.md 翻译的太烂了，多处语句不通顺，需要看英文原文才能理解，需要好好校对一下

### ISSUE THREAD

**Issue by xiezhuangping** [CocoaChina-editors/Welcome-to-Swift#133]

**Comment by dabing1022** [comment]
此仓库中的《The Swift Programming Language》一书不建议朋友再参考，建议到 [https://github.com/numbbbbb/the-swift-programming-language-in-chinese](https://github.com/numbbbbb/the-swift-programming-language-in-chinese)来学习。
